apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: go
  labels:
    app: go
spec:
  selector: 
    matchLabels: 
      app: go
  template: 
    metadata: 
      name: go-pod 
      labels: 
        app: go 
    spec: 
      containers: 
      - name: go-con 
        image: pranay1717/go-mysql-connect:latest 
        resources: 
          requests: 
            cpu: 200m 
            memory: 200Mi
        ports: 
        - containerPort: 8080
---

apiVersion: v1 
kind: Service 
metadata:
  name: go-service 
  labels: 
    app: go
spec: 
  selector:
    app: go
  ports:
  - port: 8080
    targetPort: 8080